### ISSUE TITLE
Request: CCW Flip Screen Mode

### ISSUE THREAD

**Issue by blisstik** [MiSTer-devel/Arcade-Gyruss_MiSTer#2]
Is it possible to add a flip screen mode ?

**Comment by blisstik** [comment]
A little more info - there is a Dip Switch in the OSD for Cabnet type: Upright or Cocktail. These two options do not change anything, I'm not sure if it should or not either.

**Comment by sorgelig** [comment]
keep in mind, not all arcades support 180 rotation. Sometimes it requires special changes in core and ROM. It's not something you can enable by simple switch if original HW doesn't support it.
